### ISSUE TITLE
Implement e2e tests

### ISSUE THREAD

**Issue by jewertow** [jewertow/federation#17]
**Subtasks:**

- [X] Implement a script for provisioning clusters in a specific topology. This script should be similar to kind_provisioner.sh from Istio.
- [X] The script for clusters provisioning should also set up kind-registry container that will serve images built from the source code.
- [X] Implement a test for importing services as remote, i.e. an imported service exists only in the remote cluster and not locally.

Tests should utilize `istio.io/istio/pkg/test/framework` as that package provides very convenient API for testing connectivity between various protocols.
